version: '3.3'
services:
  rabbitmq:
    hostname: rabbitmq1
    image: rabbitmq:${RABBITMQ_TAG}
    healthcheck:
      test:
        - CMD-SHELL
        - rabbitmq-diagnostics -q status
      interval: 60s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq1
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq1:/var/lib/rabbitmq  # Named volume
    networks:
      - dev
    logging:
      driver: json-file
    env_file: ./stack.env

networks:
  dev:

volumes:
  rabbitmq1: