version: '3.8'

services:
  nginx:
    image: nginx:${VERSION}
    ports:
      - "8077:80"
    volumes:
      - nginx_data:/usr/share/nginx/html  # Optional: to persist/override HTML
    networks:
      - web

volumes:
  nginx_data:

networks:
  web:
    driver: bridge