version: '3.8'

services:
  nginx:
    image: nginx:${VERSION}
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html  # optional: to persist/override HTML
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker  # or manager, depending on your setup
    networks:
      - web

volumes:
  nginx_data:

networks:
  web:
    external: false  # Set to true if you already have a 'web' network created